import 'package:get/get.dart';

class MyLocla implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "hometitle": "تطبيق ديون",
          "units": "الوحدات",
          "unit": "الوحدة",
          "category": "الاقسام",
          "product": "المنتجات",
          "requiredField": "هذا الحقل اجباري",
          "add": "اضافة ",
          "update": "تعديل",
          "loading": "جاري الارسال",
          "unitNameLable": "اسم الوحدة",
          "unitNameHint": "اسم الوحدة",
          "cancel": "الغاء",
          "confirm": "تأكيد",
          "success": "تم العملية",
          "successAdded": "تمت الاضافة بنجاح",
          "categoryNameLable": "اسم القسم",
          "categoryNameHint": "اسسم القسم",
          "comanySource": "شركات",
          "tradingSource": "تجاري",
          "productNameLable": "اسم المنتج",
          "categoryNameHint": "اسم المنتج",
          "productQuantityLable": "الكمية",
          "productQuantityHint": "الكمية",
          "productPriceLable": "سعر المنتج",
          "productPriceHint": "سعر المنتج",
          "ProductDetailsLable": "تفاصيل",
          "ProductDetailsHint": "تفاصيل",
          "productionDate": "تاريخ الانتاج",
          "expireDate": "تاريخ الانتهاء",
          "login": " تسجيل الدخول",
          "phoneNum": "رقم الهاتف",
          "loading":"جاري التحقق",
                    "1":"يمني",
          "2":"دولار",
          "3":"سعودي"
        },
        "en": {
          "hometitle": "Debt App",
          "units": "Units",
          "unit": "unit",
          "category": "categories",
          "product": "Products",
          "requiredField": "this field is required",
          "add": "Add",
          "update": "Update",
          "loading": "Loading",
          "unitNameLable": "unit name",
          "unitNameHint": "unit name",
          "cancel": "cancel",
          "confirm": "confirm",
          "success": "Auccess",
          "successAdded": "Added Successfully ",
          "categoryNameLable": "category name",
          "categoryNameHint": "category name",
          "comanySource": "company",
          "tradingSource": "trading",
          "productNameLable": "Product Name",
          "categoryNameHint": "Product Name",
          "productQuantityLable": "Quantity",
          "productQuantityHint": "Quantity",
          "productPriceLable": "Product Price",
          "productPriceHint": "Product Price",
          "ProductDetailsLable": "Details",
          "ProductDetailsHint": "Details",
          "productionDate": "Production Date ",
          "expireDate": " Expire Date",
          "login": "Login",
          "phoneNum": "phone number",
          "loading": "loading",
        }
      };
}
